/*
 * OneCheckBoxPanel.java
 *
 * Created on November 24, 2007, 8:09 PM
 */

package org.aspectj.tools.ajde.netbeans.configeditor;

import javax.swing.JCheckBox;
import org.aspectj.tools.ajde.netbeans.configeditor.AjcOptions.AjcOption;

/**
 *
 * @author  Ramos
 */
public class OneCheckBoxPanel extends javax.swing.JPanel {
    private AjcOption option;
    
    /** Creates new form OneCheckBoxPanel */
    OneCheckBoxPanel(AjcOptions.AjcOption option) {
        this.option = option;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox = new javax.swing.JCheckBox();

        checkbox.setSelected(option.isSet());
        checkbox.setText(option.getLabel());
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOptionStatus(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkbox)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateOptionStatus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOptionStatus
        // TODO add your handling code here:
        option.setSet(checkbox.isSelected());
    }//GEN-LAST:event_updateOptionStatus
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getCheckbox() {
        return checkbox;
    }
    
}
