/*
 * RelationFilterPanel.java
 *
 * Created on November 18, 2007, 9:12 AM
 */

package org.aspectj.tools.ajde.netbeans;

/**
 *
 * @author  Ramos
 */
public class RelationFilterPanel extends javax.swing.JPanel {
    
    /** Creates new form RelationFilterPanel */
    public RelationFilterPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();

        jCheckBox1.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox1.text")); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1);

        jCheckBox2.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox2.text")); // NOI18N
        add(jCheckBox2);

        jCheckBox3.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox3.text")); // NOI18N
        add(jCheckBox3);

        jCheckBox4.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox4.text")); // NOI18N
        add(jCheckBox4);

        jCheckBox5.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox5.text")); // NOI18N
        add(jCheckBox5);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1);

        jCheckBox6.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox6.text")); // NOI18N
        add(jCheckBox6);

        jCheckBox7.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox7.text")); // NOI18N
        add(jCheckBox7);

        jCheckBox8.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox8.text")); // NOI18N
        add(jCheckBox8);

        jCheckBox9.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox9.text")); // NOI18N
        add(jCheckBox9);

        jCheckBox10.setText(org.openide.util.NbBundle.getMessage(RelationFilterPanel.class, "RelationFilterPanel.jCheckBox10.text")); // NOI18N
        add(jCheckBox10);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
}
