/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ramos.relationshiptable;

import java.awt.Image;
import java.io.Serializable;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.aspectj.tools.ajde.netbeans.NbIconRegistry;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;
/**
 * Top component which displays something.
 */
final class RelationshipTableTopComponent extends TopComponent {

    private static RelationshipTableTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "RelationshipTableTopComponent";

    private RelationshipTableTopComponent() {
        initComponents();
        this.add(new RelationshipTable().getComponent());
        setName(NbBundle.getMessage(RelationshipTableTopComponent.class, "CTL_RelationshipTableTopComponent"));
        setToolTipText(NbBundle.getMessage(RelationshipTableTopComponent.class, "HINT_RelationshipTableTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized RelationshipTableTopComponent getDefault() {
        if (instance == null) {
            instance = new RelationshipTableTopComponent();
        }
        return instance;
    }

    @Override
    public Image getIcon() {
        return ((ImageIcon) NbIconRegistry.INSTANCE.getStartAjdeIcon()).getImage();
    }

    /**
     * Obtain the RelationshipTableTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized RelationshipTableTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(RelationshipTableTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof RelationshipTableTopComponent) {
            return (RelationshipTableTopComponent) win;
        }
        Logger.getLogger(RelationshipTableTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
    // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
    // TODO add custom code on component closing
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return RelationshipTableTopComponent.getDefault();
        }
    }
}
